[lint]
# D: pydocstyle
select = ["D"]
ignore = [
    "D101",
    "D200",
    "D203",
    "D212",
    "D215",
    "D404",
    "D405",
    "D406",
    "D407",
    "D408",
    "D409",
    "D410",
    "D411",
    "D412",
    "D413",
    "D414",
]
