[lint]
# D: pydocstyle
select = ["D"]
ignore = [
    "D101", # Missing docstring in public class
    "D200", # One-line docstring should fit on one line
    "D212", # Multi-line docstring summary should start at the first line
    "D405", # Section name should be properly capitalized
    "D410", # Missing blank line after section
    "D411", # Missing blank line before section
    "D412", # No blank lines allowed between a section header and its content
    "D414", # Section has no content
]

[lint.pydocstyle]
# Use Google-style docstrings.
convention = "google"
